version: '3.8'

services:
  
  db:
    image: mysql:latest
    container_name: opus_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"                      # Porta padrão do MySQL
    volumes:
      - db_data:/var/lib/mysql           # Persistência de dados

volumes:
  db_data: